//GLOBAL variables: TWO_WORDS
//LOCAL variables: twoWords 
var NUM_SLOTS =4;
var TOTAL_HEIGHT = 1000.0; // Total height of sprite 
var NUM_OFFSET = TOTAL_HEIGHT / 10;
var CHOSEN = 0;
var DEPARTMENT = "";
var DATA = {};
var PERSON = {};
var CURRENT_WINNER = null;
var PRIZES = [];
var PRIZE_INDEX = 0;
var SPIN_LEFT = 0;
var IS_SURPRISE_SPIN = true;
var BACKGROUND_PRESET = 9;
var TIME = 2000;
var REMAINING = 0;
var IS_SPINNING = false;
var WINNER = [];
var STORAGE_KEY = 'roll_winners';
var IS_IDLE = false;
var CONFETTI_TIMEOUT = [];
var BASE_HEADER_FONTSIZE = null;
var BASE_PRIZE_FONTSIZE = null;
var IS_FULLSCREEN = null;
var IS_FINISHED = true; 
var LINEAR_SPEED = TOTAL_HEIGHT / TIME;
var IS_EXPORTED = false;
var IS_FILE_LOADED = false;
var IS_ALLOW_REPICK = false;